// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmgMOqgrYYQfbex9xamrFSmCGC5O9i4X8',
    appId: '1:670737310373:web:0ac0d5ac6a54980021a34c',
    messagingSenderId: '670737310373',
    projectId: 'myfanpage5',
    authDomain: 'myfanpage5.firebaseapp.com',
    storageBucket: 'myfanpage5.appspot.com',
    measurementId: 'G-9WKJVYCQ6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgQCzqELO2pFXhHxh7_ODDeW7TqF7JCC8',
    appId: '1:670737310373:android:1c2e56537682f90421a34c',
    messagingSenderId: '670737310373',
    projectId: 'myfanpage5',
    storageBucket: 'myfanpage5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ychsJcgtHT2ddscfdIGTPRoMYpC66dY',
    appId: '1:670737310373:ios:3c301da33fcaf03721a34c',
    messagingSenderId: '670737310373',
    projectId: 'myfanpage5',
    storageBucket: 'myfanpage5.appspot.com',
    iosClientId: '670737310373-46k8ii2opjtnrdahu0luh3b45csdu9hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fanApp',
  );
}
